# Global default environment
container:
  image: python:slim

task:
  name: Build and Run
  install_git_script:
    - apt-get update
    - apt-get upgrade -y
    - apt-get install -y git
  pip_cache:
    folder: ~/.cache/pip
    fingerprint_script: echo $PYTHON_VERSION && cat requirements.txt
    populate_script: pip install -r requirements.txt
  pip_install_script: pip install -r requirements.txt
  fetch_git_tags_script: git fetch --tags
  install_script: python setup.py install
  version_script: self-updating-app --version
  test_script: self-updating-app

