# Global default environment
container:
  image: python:slim

task:
  name: Build and Run
  pip_cache:
    folder: ~/.cache/pip
    fingerprint_script: echo $PYTHON_VERSION && cat requirements.txt
    populate_script: pip install -r requirements.txt
  build_script: python setup.py develop
  # install_script: python setup.py install
  version_script: self-updating-app --version
  run_script: self-updating-app

